package ratelimit
// Package ratelimit provides rate limiting utilities for API requests







































































var GlobalLimiter = NewLimiter(100, time.Minute/100)// Allows 100 requests per minute per function// Global rate limiter for Cloud Functions}	return b	}		return a	if a < b {func min(a, b int) int {}	l.lastRefill = time.Now()	l.tokens = l.capacity		defer l.mu.Unlock()	l.mu.Lock()func (l *Limiter) Reset() {// Reset resets the limiter to full capacity}	return false		}		return true		l.tokens--	if l.tokens > 0 {	// Check if we have tokens available		}		l.lastRefill = now		l.tokens = min(l.capacity, l.tokens+refills)	if refills > 0 {		refills := int(elapsed / l.refillRate)	elapsed := now.Sub(l.lastRefill)	now := time.Now()	// Refill tokens based on time elapsed		defer l.mu.Unlock()	l.mu.Lock()func (l *Limiter) Allow() bool {// Allow checks if a request is allowed under the rate limit}	}		lastRefill: time.Now(),		refillRate: refillRate,		capacity:   capacity,		tokens:     capacity,	return &Limiter{func NewLimiter(capacity int, refillRate time.Duration) *Limiter {// refillRate: duration between token refills// capacity: maximum number of tokens// NewLimiter creates a new rate limiter}	lastRefill time.Time	refillRate time.Duration	capacity int	tokens   int	mu       sync.Mutextype Limiter struct {// Limiter implements a token bucket rate limiter)	"time"	"sync"import (package ratelimit