package main
package main

import (
	"errors"
	"strings"
	"testing"
)

func TestValidateTopicInput(t *testing.T) {
	tests := []struct {
		name    string
		topic   string
		wantErr error











































































































































}	}		})			}				t.Errorf("MapErrorToResponse() Error message is empty")			if got.Error == "" {			}				t.Errorf("MapErrorToResponse() Retryable = %v, want true", got.Retryable)			if !got.Retryable {			}				t.Errorf("MapErrorToResponse() Code = %v, want %v", got.Code, tt.wantCode)			if got.Code != tt.wantCode {			got := MapErrorToResponse(tt.err)		t.Run(tt.name, func(t *testing.T) {	for _, tt := range tests {	}		},			wantCode: ErrInternalError,			err:      errors.New("some other error"),			name:     "unknown error",		{		},			wantCode: ErrInvalidTopicContent,			err:      ErrTopicInvalid,			name:     "topic invalid",		{		},			wantCode: ErrInvalidTopicLength,			err:      ErrTopicTooLong,			name:     "topic too long",		{		},			wantCode: ErrInvalidTopicLength,			err:      ErrTopicTooShort,			name:     "topic too short",		{	}{		wantCode string		err      error		name     string	tests := []struct {func TestMapErrorToResponse(t *testing.T) {}	}		})			}				t.Errorf("SanitizeTopic() = %v, want %v", got, tt.want)			if got != tt.want {			got := SanitizeTopic(tt.topic)		t.Run(tt.name, func(t *testing.T) {	for _, tt := range tests {	}		},			want:  "Should Christians defy authorities when the law is unfair?",			topic: "Should Christians defy authorities when the law is unfair?",			name:  "clean topic unchanged",		{		},			want:  "alert('xss')Should Christians defy authorities?",			topic: "<script>alert('xss')</script>Should Christians defy authorities?<img src=x>",			name:  "remove multiple HTML tags",		{		},			want:  "Should Christians defy authorities?",			topic: "Should   Christians    defy   authorities?",			name:  "normalize whitespace",		{		},			want:  "Should Christians defy authorities?",			topic: "  Should Christians defy authorities?  ",			name:  "trim whitespace",		{		},			want:  "Should Christians defy authorities?",			topic: "Should Christians <b>defy</b> authorities?",			name:  "remove HTML tags",		{	}{		want  string		topic string		name  string	tests := []struct {func TestSanitizeTopic(t *testing.T) {}	}		})			}				t.Errorf("ValidateTopicInput() error = %v, wantErr %v", err, tt.wantErr)			if !errors.Is(err, tt.wantErr) {			err := ValidateTopicInput(tt.topic)		t.Run(tt.name, func(t *testing.T) {	for _, tt := range tests {	}		},			wantErr: nil,			topic:   strings.Repeat("a", 500), // Exactly 500 characters			name:    "maximum valid length",		{		},			wantErr: nil,			topic:   "0123456789", // Exactly 10 characters			name:    "minimum valid length",		{		},			wantErr: ErrTopicInvalid,			topic:   "Should Christians &lt;script&gt; defy authorities?",			name:    "topic with HTML entities",		{		},			wantErr: ErrTopicInvalid,			topic:   "Should Christians <script>alert('xss')</script> defy authorities?",			name:    "topic with HTML tags",		{		},			wantErr: ErrTopicTooLong,			topic:   strings.Repeat("a", 501),			name:    "topic too long",		{		},			wantErr: ErrTopicTooShort,			topic:   "Short",			name:    "topic too short",		{		},			wantErr: nil,			topic:   "  Should Christians defy authorities?  ",			name:    "topic with extra whitespace",		{		},			wantErr: nil,			topic:   "Should Christians defy authorities when the law is unfair?",			name:    "valid topic",		{	}{