package auth
// Package auth provides API key management and authentication utilities



















































}	return string(result.Payload.Data), nil		}		return "", fmt.Errorf("failed to access secret %s: %w", secretID, err)	if err != nil {	result, err := client.AccessSecretVersion(ctx, req)		}		Name: name,	req := &secretmanagerpb.AccessSecretVersionRequest{	// Access the secret		name := fmt.Sprintf("projects/%s/secrets/%s/versions/latest", projectID, secretID)	// Build the secret version name		defer client.Close()	}		return "", fmt.Errorf("failed to create secret manager client: %w", err)	if err != nil {	client, err := secretmanager.NewClient(ctx)func getFromSecretManager(ctx context.Context, projectID, secretID string) (string, error) {// getFromSecretManager retrieves a secret from GCP Secret Manager}	return getFromSecretManager(ctx, projectID, "anthropic-api-key")		}		return "", fmt.Errorf("neither ANTHROPIC_API_KEY nor GCP_PROJECT_ID is set")	if projectID == "" {	projectID := os.Getenv("GCP_PROJECT_ID")	// Fall back to GCP Secret Manager for production		}		return apiKey, nil	if apiKey := os.Getenv("ANTHROPIC_API_KEY"); apiKey != "" {	// Try environment variable first (for local development)func GetAnthropicAPIKey(ctx context.Context) (string, error) {// First checks environment variable, then falls back to GCP Secret Manager// GetAnthropicAPIKey retrieves the Anthropic API key)	"cloud.google.com/go/secretmanager/apiv1/secretmanagerpb"	secretmanager "cloud.google.com/go/secretmanager/apiv1"	"os"	"fmt"	"context"import (package auth